# Site settings
title: ΔΨφ
description: A blog featuring Physics and Advanced Math, focusing mainly on Particle Physics and Quantum Computing
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ΔΨφ
user_description: I love physics and math
user_title: Editor-in-Chief
email: deltapsifi@outlook.com
github_username:  deltapsifi
author: ΔΨφ

sidebars:
  - title: Home
    url: /
  - title: Articles
    subfolderitems:
      - page: Condensed Matter Physics
        url: 
      - page: Quantum Mechanics
        url: 
      - page: Quantum Computing
        url: 
      - page: Advanced Math
        url:
      - page: Standard Model
        url: 
  - title: About Me
    url: /about.html
  - title: Contact Me
    url: 


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
